apiVersion: v1
kind: Service
metadata:
  name: ba
  namespace: default
spec:
  selector:
    app: ba
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ba
  namespace: default
  labels:
    app: ba
spec:
  selector:
    matchLabels:
      app: ba
  template:
    metadata:
      labels:
        app: ba
    spec:
      containers:
        - name: ba
          image: maximeschwarzer/ba-backend:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: PROMETHEUS_URL
              valueFrom:
                configMapKeyRef:
                  name: ba-config
                  key: PROMETHEUS_URL
      serviceAccountName: default
