apiVersion: v1
kind: Service
metadata:
  name: ba-frontend
  namespace: default
spec:
  selector:
    app: ba-frontend
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ba-frontend
  namespace: default
  labels:
    app: ba-frontend
spec:
  selector:
    matchLabels:
      app: ba-frontend
  template:
    metadata:
      labels:
        app: ba-frontend
    spec:
      containers:
        - name: ba-frontend
          image: maximeschwarzer/ba-frontend:latest
          ports:
            - containerPort: 9001
          imagePullPolicy: Always
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: 00-config-ba-frontend
                  key: API_URL
      serviceAccountName: default
