apiVersion: v1
kind: Service
metadata:
  name: expa-backend
  namespace: default
spec:
  selector:
    app: expa-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expa-backend
  namespace: default
  labels:
    app: expa-backend
spec:
  selector:
    matchLabels:
      app: expa-backend
  template:
    metadata:
      labels:
        app: expa-backend
    spec:
      containers:
        - name: expa-backend
          image: maximeschwarzer/ba-backend:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always
          env:
            - name: PROMETHEUS_URL
              valueFrom:
                configMapKeyRef:
                  name: expa-backend-config
                  key: PROMETHEUS_URL
      serviceAccountName: default
