apiVersion: v1
kind: Service
metadata:
  name: expa-frontend
  namespace: default
spec:
  selector:
    app: expa-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9001

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: expa-frontend
  namespace: default
  labels:
    app: expa-frontend
spec:
  selector:
    matchLabels:
      app: expa-frontend
  template:
    metadata:
      labels:
        app: expa-frontend
    spec:
      containers:
        - name: expa-frontend
          image: maximeschwarzer/ba-frontend:latest
          ports:
            - containerPort: 9001
          imagePullPolicy: Always
          env:
            - name: API_URL
              valueFrom:
                configMapKeyRef:
                  name: 00-config-expa-frontend
                  key: API_URL
      serviceAccountName: default
