apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: expa-frontend-ingress
  namespace: default
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: expa-frontend
      port:
        number: 80